#server port configuration
server:
  port: 8081
  servlet:
    context-path: /MySpringWebApp

#view resolver configuration
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

#Application messeges
myapp:
  properties:
   regSuccess: Registration Successful...
   regFail: Registration Fail...
   logSuccess: Login Successful...
   logFail: Login Fail...
   bookSuccess: Book added successfully...
   bookDelete: Book deleted successfully...
   bookUpdate: Book updated successfully...
   